---
- name: create kubeconfig directory
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: '{{ kubernetes.certificate.directory }}/kubeconfig/'}

- name: generate kubeconfig for client
  args:
    chdir: "{{ kubernetes.certificate.directory }}/kubeconfig/"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
        --certificate-authority={{ kubernetes.certificate.directory }}/intermediates/kubernetes-ca/kubernetes-ca.pem \
        --embed-certs=true \
        --server=https://{{ infrastructure.keepalived.virtualIP }}:{{ infrastructure.keepalived.virtualIPPort }} \
        --kubeconfig=client.kubeconfig

    kubectl config set-credentials admin \
        --client-certificate={{ kubernetes.certificate.directory }}/certificates/kubernetes-admin/kubernetes-admin.pem \
        --client-key={{ kubernetes.certificate.directory }}/certificates/kubernetes-admin/kubernetes-admin-key.pem \
        --embed-certs=true \
        --kubeconfig=client.kubeconfig

    kubectl config set-context {{ kubernetes.clusterName }} \
        --cluster={{ kubernetes.clusterName }} \
        --user=admin \
        --kubeconfig=client.kubeconfig

    kubectl config use-context {{ kubernetes.clusterName }} --kubeconfig=client.kubeconfig

- name: create .kube directory
  file:
    path: /home/{{ user }}/.kube/
    state: directory

- name: Copy client.kubeconfig to .kube directory
  copy: 
    src: "{{ kubernetes.certificate.directory }}/kubeconfig/client.kubeconfig"
    dest: "/home/{{ user }}/.kube/config"
    remote_src: yes
  
- name: generate kubeconfig for client oidc
  args:
    chdir: "{{ kubernetes.certificate.directory }}/kubeconfig/"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
        --certificate-authority={{ kubernetes.certificate.directory }}/intermediates/kubernetes-ca/kubernetes-ca.pem \
        --embed-certs=true \
        --server=https://{{ infrastructure.keepalived.virtualIP }}:{{ infrastructure.keepalived.virtualIPPort }} \
        --kubeconfig=client-oidc.kubeconfig
  when: kubernetes.addonsComponents.oidc.enabled
