- name: create flannel from template
  template:
    src: "flannel.yml.j2"
    dest: "~/flannel-{{ kubernetes.addonsComponents.flannel.version }}.yml"
  when: inventory_hostname == '{{ infrastructure.keepalived.masterIP }}'
  
- name: apply flannel template
  shell: kubectl apply -f ~/flannel-{{ kubernetes.addonsComponents.flannel.version }}.yml
  when: inventory_hostname == '{{ infrastructure.keepalived.masterIP }}'

- name: pause 1 minute
  pause:
    minutes: 1
