- name: create runtime-class from template
  template:
    src: "runtime-class.yml.j2"
    dest: "~/runtime-class.yml"
  when: kubernetes.components.gvisor.enabled
  
- name: apply runtime-class template
  shell: kubectl apply -f ~/runtime-class.yml
  when: kubernetes.components.gvisor.enabled
